workflows:
  expo-apk-build:
    name: Build Expo APK for MathTutorApp
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: EncryptedExpoTokenGoesHere
      node: 18.16.0
    scripts:
      - name: Install Expo CLI and EAS CLI
        script: |
          npm install -g expo-cli eas-cli
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/app.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
